$ModuleName = ".\CredentialManager.psd1"
#$test = get-item $ModuleName
#if (Test-Path $test) {Remove-Item $ModuleName}
#
# Module manifest for module 'CredentialManager'
#
# Generated by: Jay Pieren
#
# Generated on: July 2020
#
$manifest = @{
    RootModule = 'CredentialManager.psm1'
    ModuleVersion = '1.0.0'
    GUID = 'e1826c6e-c420-4eef-9ac8-185e3669ca6a'
    Author = 'Jay Pieren'
    CompanyName = 'Eagle Communications Ltd.'
    Copyright = '(c) Eagle Communications Ltd. All rights reserved.'
    Description = 'Module to Manage Passwords safely'
    PowerShellVersion = '3.0'
    ProcessorArchitecture = 'amd64'
    CmdletsToExport = @('Get-PasswordHash')
    FunctionsToExport = @('Get-PasswordHash')
    VariablesToExport = '*'
    AliasesToExport = @()
     FileList = @(
    '.\CredentialManager.psm1',
    '.\CredentialManager.psd1',
    'README.cmd',
    'sample-use.ps1'
    )
    PrivateData = @{
        PSData = @{
            Tags = @('credentials','security','automation')
            ProjectUri = 'https://github.com/jpieren/CredentialManagement.git'
            #ReleaseNotes = 'https://github.com/jpieren/CredentialManagement/blob/master/README.md'
        } # End of PSData hashtable
    } # End of PrivateData hashtable

    HelpInfoURI = 'https://github.com/jpieren/CredentialManagement/blob/master/README.md'
    Path = $ModuleName
}
New-ModuleManifest @manifest